source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails'       , '4.1.6'
gem 'sass-rails'  , '4.0.3'
gem 'uglifier'    , '2.5.3'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.1.2' 
gem 'turbolinks'  , '2.4.0'
gem 'jbuilder'    , '2.2.2'
gem 'rails-html-sanitizer', '1.0.1'
gem 'sdoc'        , '0.4.1',          group: :doc
   
group :development, :test do
  gem 'sqlite3'      , '1.3.9'
  gem 'byebug'       , '3.5.1'
  gem 'web-console'  , '1.0.4'
  gem 'spring'       , '1.1.3' 
end

group :production do
  gem 'pg'                 , '0.17.1'
  gem 'rails_12factor'     , '0.0.2' 
end

